APP_ENV=local
APP_DEBUG=true
APP_KEY=tpnkydZWClkutu3xfQw4ocW0yUGF1PHb

DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=porcinos
DB_USERNAME=root
DB_PASSWORD=

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=yuliamaya099@gmail.com
MAIL_PASSWORD=@3123453533@@@
MAIL_ENCRYPTION=ssl
